[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.build]
disabled = true

[tasks.test]
disabled = true

[tasks.compose-up]
script_runner = "@shell"
script = '''
docker-compose up -d
'''

[tasks.compose-down]
script_runner = "@shell"
script = '''
docker-compose down
'''

[tasks.remove-volumes]
script_runner = "@shell"
script = '''
docker volume prune --filter all=1
'''

# Grafana

[tasks.compose-grafana]
script_runner = "@shell"
script = '''
docker compose down grafana
docker compose up -d --no-deps --force-recreate --build grafana
'''

# Prometheus

[tasks.compose-prometheus]
script_runner = "@shell"
script = '''
docker compose down prometheus
docker compose up -d --no-deps --force-recreate --build prometheus
'''

# Prometheus

[tasks.compose-rabbitmq]
script_runner = "@shell"
script = '''
docker compose down rabbitmq
docker compose up -d --no-deps --force-recreate --build rabbitmq
'''

# Proxy server

[tasks.build-proxy]
script_runner = "@shell"
script = '''
cross build --release --package proxy --target x86_64-unknown-linux-musl
rm -f ./bin/proxy
cp ./target/x86_64-unknown-linux-musl/release/proxy ./bin/proxy
'''

[tasks.compose-proxy]
script_runner = "@shell"
script = '''
docker compose down proxy-svc
docker compose up -d --no-deps --force-recreate --build proxy-svc
'''

[tasks.proxy]
dependencies = ["build-proxy", "compose-proxy"]

# Access server

[tasks.build-access]
script_runner = "@shell"
script = '''
cross build --release --package access --target x86_64-unknown-linux-musl
rm -f ./bin/access
rm -rf ./cfg/access
cp ./target/x86_64-unknown-linux-musl/release/access ./bin/access
cp -rf ./api/access/res/assets/* ./cfg/access/*
'''

[tasks.compose-access]
script_runner = "@shell"
script = '''
docker compose down access-svc
docker compose up -d --no-deps --force-recreate --build access-svc
'''

[tasks.access]
dependencies = ["build-access", "compose-access"]

# Logger service

[tasks.build-logger]
script_runner = "@shell"
script = '''
cross build --release --package logger --target x86_64-unknown-linux-musl
rm -f ./bin/logger
cp ./target/x86_64-unknown-linux-musl/release/logger ./bin/logger
'''

[tasks.compose-logger]
script_runner = "@shell"
script = '''
docker compose down logger-svc
docker compose up -d --no-deps --force-recreate --build logger-svc
'''

[tasks.logger]
dependencies = ["build-logger", "compose-logger"]

# System service

[tasks.build-system]
script_runner = "@shell"
script = '''
cross build --release --package system --target x86_64-unknown-linux-musl
rm -f ./bin/system
cp ./target/x86_64-unknown-linux-musl/release/system ./bin/system
'''

[tasks.compose-system]
script_runner = "@shell"
script = '''
docker compose down system-svc
docker compose up -d --no-deps --force-recreate --build system-svc
'''

[tasks.system]
dependencies = ["build-system", "compose-system"]

# Audit service

[tasks.build-audit]
script_runner = "@shell"
script = '''
cross build --release --package audit --target x86_64-unknown-linux-musl
rm -f ./bin/audit
rm -rf ./cfg/audit
cp ./target/x86_64-unknown-linux-musl/release/audit ./bin/audit
cp -rf ./api/audit/res/assets/* ./cfg/audit/*
'''

[tasks.compose-audit]
script_runner = "@shell"
script = '''
docker compose down audit-svc
docker compose up -d --no-deps --force-recreate --build audit-svc
'''

[tasks.audit]
dependencies = ["build-audit", "compose-audit"]

# Batch tasks

[tasks.build-api]
dependencies = ["build-logger", "build-system", "build-access", "build-audit", "buid-proxy"]

[tasks.compose-api]
dependencies = ["compose-logger", "compose-system", "compose-access", "compose-audit", "compose-proxy"]

[tasks.install-dioxus]
install_crate = "dioxus-cli"

[tasks.install-cross]
install_crate = "cross"