global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
#          - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
  - job_name: "system-service"
    static_configs:
      - targets: ["system:3001"]
  - job_name: "access-service"
    static_configs:
      - targets: ["access:3001"]
  - job_name: "proxy-service"
    static_configs:
      - targets: ["proxy:3001"]